spring:
    application:
        name: bbs
    datasource:
        url: jdbc:mysql://localhost:3306/hnubbs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    '[com.hnu.bbs]': info

server:
  port: 8000
